# Generated by Django 5.1.3 on 2024-11-25 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('mapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.kecamatan'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.provinsi'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='regency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.kabupatenkota'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mapping.kelurahandesa'),
        ),
    ]
