# Generated by Django 4.2.16 on 2024-11-26 04:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_warehouse_district_alter_warehouse_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='ID'),
        ),
    ]
